### PR TITLE
Fixed duplicate tag-bug  (#45)

### PR DESCRIPTION
**Pull request by Agreon**

### CODE REVIEW

**Comment by mjdubell** [comment]
The good: The change works, no more duplicate tags
The Bad: Removing a tag removes all tags from the client (if you refresh the page you can see the remaining tags)

**Comment by Agreon** [comment]
I cannot reproduce this. And i don't think my fix caused this problem.

**Comment by mjdubell** [comment]
@Agreon Which browser are you using?

**Comment by Agreon** [comment]
Firefox, but i think the problem is that you identify tags by their labels. So if you add "bug1" 2x, and later on delete tags with label "bug1", both get deleted. 
Maybe you should check in the Event-Listener if a tag with the label is already added.
See below: 
`
          e.target.value
            .split(',')
            .filter(tag => !tags.includes(tag))
            .forEach(tag => {
              tags.push(tag);  
            });
`

**Comment by mjdubell** [comment]
@Agreon That could be the issue, but removing the comment obviously had negative effects. If you think you can solve the problem entirely, send a PR and i''ll merge it 😃

**Pull request closed without merging**
